addons:
  apt:
    sources:
    - llvm-toolchain-precise
    packages:
    - clang-3.8

install:
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.8"; fi


compiler: clang
language: cpp
script: make -B -C src test